premiosplatziapp/polis/urls.py
from django.urls import path

from . import views

app_name = "polis"

urlpatterns = [
    #ex: /polis/
    path("",views.IndexView.as_view(),name="index"),
    #ex: /polis/5
    path("<int:pk>/detail/",views.DetailView.as_view(),name="detail"),
    #ex: /polis/5/results
    path("<int:pk>/results/",views.ResultsView.as_view(),name="results"),
    #ex: /polis/vote
    path("<int:question_id>/vote/",views.vote,name="vote"),
]

premiosplatziapp/premiosplatziapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polis/", include("polis.urls"))
]

premiosplatziapp/polis/models.py
from datetime import datetime
from pyexpat import model
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=150)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)        
    
    
class Choice(models.Model):
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=150)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

premiosplatziapp/polis/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

# # Create your views here.
# def index(request):
#     latest_question_list = Question.objects.all()
#     return render(request,"polis/index.html",{
#         "latest_question_list": latest_question_list
#     })


# def detail(request,question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request,"polis/detail.html",{
#         "question": question
#     })


# def results(request,question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request, "polis/results.html",{
#         "question": question
#     })


class IndexView(generic.ListView):
    template_name = "polis/index.html"
    context_object_name = "latest_question_list"
    
    def get_queryset(self):
        """Return the last five published questions"""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polis/detail.html"
    

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polis/results.html"    


def vote(request,question_id):
    question = get_object_or_404(Question ,pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError,Choice.DoesNotExist):
        return render(request,"polis/detail.html",{
            "question": question,
            "error_message": "No eligiste una respuesta"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polis:results",args=(question.id,)))

premiosplatziapp/polis/templates/polis/detail.html
{% comment %} <h1>{{question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}}</li>
    {% endfor %}
</ul> {% endcomment %}

<form action="{% url 'polis:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{question.question_text}}</h1></legend>
    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
        <br>
    {% endfor %}
</fieldset>
<input type="submit" value="votar">
</form>

premiosplatziapp/polis/templates/polis/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polis:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %} 
    </ul>
{% else %}
    <p>No polis are available.</p>
{% endif %}

premiosplatziapp/polis/templates/polis/results.html
<h1>{{question.question_text}}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes | pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'polis:detail' question.id %}">Te gustaria votar de nuevo?</a>